image: golang:latest

variables:
  GOPATH: $CI_PROJECT_DIR/.go

cache:
  key: gomod
  paths:
    - $GOPATH/pkg/mod

before_script:
  - go mod download

stages:
  - quality
  - build

lint:
  before_script:
    - go get -u -v golang.org/x/lint/golint
    - export PATH=$PATH:$CI_PROJECT_DIR/.go/bin
  stage: quality
  script:
    - test -z $(gofmt -s -l cmd/ pkg/)
    - go vet ./...
    - golint -set_exit_status ./...

test:
  stage: quality
  script:
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - CGO_ENABLED=0 go build -ldflags "-extldflags '-static' -s -w" ./cmd/tk
  artifacts:
    paths:
      - tk
