version: "2"
linters:
  settings:
    revive:
      rules:
        - name: var-naming
          disabled: true
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        - "-QF1001"
        - "-QF1008"
  enable:
    - copyloopvar
    - dogsled
    - goconst
    - gocritic
    - misspell
    - revive
    - staticcheck
    - unconvert
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
