name: setup-goversion
runs:
  using: composite
  steps:
    - id: goversion
      run: |
        cat Dockerfile | awk '/^FROM golang:.* AS build$/ {v=$2;split(v,a,":"); split(a[2],b,"@")}; END {printf("version=%s", b[1])}' >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: "${{steps.goversion.outputs.version}}"
