---
kind: pipeline
name: check
steps:
- commands:
  - go mod download
  image: golang:1.20
  name: download
  volumes:
  - name: gopath
    path: /go
- commands:
  - if [ ! -f linux-amd64/helm ]; then
  - '  wget -q https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz'
  - '  tar -zxvf helm-v3.9.0-linux-amd64.tar.gz'
  - '  rm -f helm-v3.9.0-linux-amd64.tar.gz'
  - fi
  - cp linux-amd64/helm /usr/local/bin/helm
  - go install github.com/google/go-jsonnet/cmd/jsonnet@v0.20.0
  - make lint
  image: golang:1.20
  name: lint
  volumes:
  - name: gopath
    path: /go
- commands:
  - if [ ! -f linux-amd64/helm ]; then
  - '  wget -q https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz'
  - '  tar -zxvf helm-v3.9.0-linux-amd64.tar.gz'
  - '  rm -f helm-v3.9.0-linux-amd64.tar.gz'
  - fi
  - cp linux-amd64/helm /usr/local/bin/helm
  - go install github.com/google/go-jsonnet/cmd/jsonnet@v0.20.0
  - make test
  image: golang:1.20
  name: test
  volumes:
  - name: gopath
    path: /go
- commands:
  - if [ ! -f linux-amd64/helm ]; then
  - '  wget -q https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz'
  - '  tar -zxvf helm-v3.9.0-linux-amd64.tar.gz'
  - '  rm -f helm-v3.9.0-linux-amd64.tar.gz'
  - fi
  - cp linux-amd64/helm /usr/local/bin/helm
  - go install github.com/google/go-jsonnet/cmd/jsonnet@v0.20.0
  - make cross
  image: golang:1.20
  name: build
  volumes:
  - name: gopath
    path: /go
trigger:
  ref:
  - refs/pull/*/head
  - refs/heads/main
volumes:
- name: gopath
  temp: {}
---
kind: pipeline
name: benchmark against main
node:
  type: no-parallel
steps:
- commands:
  - go install github.com/google/go-jsonnet/cmd/jsonnet@v0.20.0
  - go test -bench=. -benchmem -count=6 -run=^$ ./... | tee bench-pr.txt
  - git fetch origin main
  - git reset --hard origin/main
  - go test -bench=. -benchmem -count=6 -run=^$ ./... | tee bench-main.txt
  - go install golang.org/x/perf/cmd/...@latest
  - benchstat bench-main.txt bench-pr.txt
  image: golang:1.20
  name: benchmark
  volumes:
  - name: gopath
    path: /go
trigger:
  ref:
  - refs/pull/*/head
volumes:
- name: gopath
  temp: {}
---
depends_on:
- check
kind: pipeline
name: release
steps:
- commands:
  - git fetch origin --tags
  image: golang:1.20
  name: fetch-tags
  volumes:
  - name: gopath
    path: /go
- commands:
  - if [ ! -f linux-amd64/helm ]; then
  - '  wget -q https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz'
  - '  tar -zxvf helm-v3.9.0-linux-amd64.tar.gz'
  - '  rm -f helm-v3.9.0-linux-amd64.tar.gz'
  - fi
  - cp linux-amd64/helm /usr/local/bin/helm
  - go install github.com/google/go-jsonnet/cmd/jsonnet@v0.20.0
  - make cross
  image: golang:1.20
  name: cross
  volumes:
  - name: gopath
    path: /go
- image: plugins/github-release
  name: publish
  settings:
    api_key:
      from_secret: grafanabot_pat
    draft: true
    files: dist/*
    note: |
      This is release ${DRONE_TAG} of Tanka (`tk`). Check out the [CHANGELOG](https://github.com/grafana/tanka/blob/main/CHANGELOG.md) for detailed release notes.
      ## Install instructions

      #### Binary:
      ```bash
      # download the binary (adapt os and arch as needed)
      $ curl -fSL -o "/usr/local/bin/tk" "https://github.com/grafana/tanka/releases/download/${DRONE_TAG}/tk-linux-amd64"

      # make it executable
      $ chmod a+x "/usr/local/bin/tk"

      # have fun :)
      $ tk --help
      ```

      #### Docker container:
      https://hub.docker.com/r/grafana/tanka
      ```bash
      $ docker pull grafana/tanka:${DRONE_TAG#v}
      ```
    title: ${DRONE_TAG}
trigger:
  ref:
  - refs/tags/v*
volumes:
- name: gopath
  temp: {}
---
depends_on:
- check
kind: pipeline
name: docker-amd64
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - git fetch origin --tags
  image: golang:1.20
  name: fetch-tags
  volumes:
  - name: gopath
    path: /go
- commands:
  - if [ ! -f linux-amd64/helm ]; then
  - '  wget -q https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz'
  - '  tar -zxvf helm-v3.9.0-linux-amd64.tar.gz'
  - '  rm -f helm-v3.9.0-linux-amd64.tar.gz'
  - fi
  - cp linux-amd64/helm /usr/local/bin/helm
  - go install github.com/google/go-jsonnet/cmd/jsonnet@v0.20.0
  - make static
  image: golang:1.20
  name: static
  volumes:
  - name: gopath
    path: /go
- image: plugins/docker
  name: container
  settings:
    auto_tag: true
    auto_tag_suffix: amd64
    password:
      from_secret: dockerhub_password
    repo: grafana/tanka
    username:
      from_secret: dockerhub_username
trigger:
  ref:
  - refs/tags/v*
  - refs/heads/main
volumes:
- name: gopath
  temp: {}
---
depends_on:
- check
kind: pipeline
name: docker-arm64
platform:
  arch: arm64
  os: linux
steps:
- commands:
  - git fetch origin --tags
  image: golang:1.20
  name: fetch-tags
  volumes:
  - name: gopath
    path: /go
- commands:
  - if [ ! -f linux-amd64/helm ]; then
  - '  wget -q https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz'
  - '  tar -zxvf helm-v3.9.0-linux-amd64.tar.gz'
  - '  rm -f helm-v3.9.0-linux-amd64.tar.gz'
  - fi
  - cp linux-amd64/helm /usr/local/bin/helm
  - go install github.com/google/go-jsonnet/cmd/jsonnet@v0.20.0
  - make static
  image: golang:1.20
  name: static
  volumes:
  - name: gopath
    path: /go
- image: plugins/docker
  name: container
  settings:
    auto_tag: true
    auto_tag_suffix: arm64
    password:
      from_secret: dockerhub_password
    repo: grafana/tanka
    username:
      from_secret: dockerhub_username
trigger:
  ref:
  - refs/tags/v*
  - refs/heads/main
volumes:
- name: gopath
  temp: {}
---
depends_on:
- docker-amd64
- docker-arm64
kind: pipeline
name: manifest-main
steps:
- commands:
  - git fetch origin --tags
  - echo "main-$(git describe --tags)" > .tags
  image: golang:1.20
  name: fetch-tags
  volumes:
  - name: gopath
    path: /go
- image: plugins/manifest:1.4.0
  name: manifest
  settings:
    ignore_missing: true
    password:
      from_secret: dockerhub_password
    spec: .drone/docker-manifest.tmpl
    username:
      from_secret: dockerhub_username
trigger:
  ref:
  - refs/heads/main
volumes:
- name: gopath
  temp: {}
---
depends_on:
- docker-amd64
- docker-arm64
kind: pipeline
name: manifest
steps:
- image: plugins/manifest:1.4.0
  name: manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: dockerhub_password
    spec: .drone/docker-manifest.tmpl
    username:
      from_secret: dockerhub_username
trigger:
  ref:
  - refs/tags/v*
  - refs/heads/main
volumes:
- name: gopath
  temp: {}
---
get:
  name: pat
  path: infra/data/ci/github/grafanabot
kind: secret
name: grafanabot_pat
---
get:
  name: username
  path: infra/data/ci/docker_hub
kind: secret
name: dockerhub_username
---
get:
  name: password
  path: infra/data/ci/docker_hub
kind: secret
name: dockerhub_password
---
kind: signature
hmac: d6e20fdf35f6a2177b563a0db363b55872b276a880165349685c1f6aa1641495

...
