---
kind: pipeline
name: check
steps:
- commands:
  - go mod download
  image: golang:1.16
  name: download
  volumes:
  - name: gopath
    path: /go
- commands:
  - make lint
  depends_on:
  - download
  image: golang:1.16
  name: lint
  volumes:
  - name: gopath
    path: /go
- commands:
  - make test
  depends_on:
  - download
  image: golang:1.16
  name: test
  volumes:
  - name: gopath
    path: /go
volumes:
- name: gopath
  temp: {}
---
depends_on:
- check
kind: pipeline
name: release
steps:
- commands:
  - git fetch origin --tags
  image: golang:1.16
  name: fetch-tags
  volumes:
  - name: gopath
    path: /go
- commands:
  - make cross
  image: golang:1.16
  name: cross
  volumes:
  - name: gopath
    path: /go
- image: plugins/github-release
  name: publish
  settings:
    api_key:
      from_secret: grafanabot_pat
    draft: true
    files: dist/*
    note: |
      This is release ${DRONE_TAG} of Tanka (`tk`). Check out the [CHANGELOG](https://github.com/grafana/tanka/blob/main/CHANGELOG.md) for detailed release notes.
      ## Install instructions

      #### Binary:
      ```bash
      # download the binary (adapt os and arch as needed)
      $ curl -fSL -o "/usr/local/bin/tk" "https://github.com/grafana/tanka/releases/download/${DRONE_TAG}/tk-linux-amd64"

      # make it executable
      $ chmod a+x "/usr/local/bin/tk"

      # have fun :)
      $ tk --help
      ```

      #### Docker container:
      https://hub.docker.com/r/grafana/tanka
      ```bash
      $ docker pull grafana/tanka:${DRONE_TAG#v}
      ```
    title: ${DRONE_TAG}
trigger:
  event:
  - tag
volumes:
- name: gopath
  temp: {}
---
depends_on:
- check
kind: pipeline
name: docker-amd64
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - git fetch origin --tags
  image: golang:1.16
  name: fetch-tags
  volumes:
  - name: gopath
    path: /go
- commands:
  - make static
  image: golang:1.16
  name: static
  volumes:
  - name: gopath
    path: /go
- image: plugins/docker
  name: container
  settings:
    auto_tag: true
    auto_tag_suffix: amd64
    password:
      from_secret: dockerhub_password
    repo: grafana/tanka
    username:
      from_secret: dockerhub_username
trigger:
  ref:
  - refs/heads/main
  - refs/heads/docker
  - refs/tags/v*
volumes:
- name: gopath
  temp: {}
---
depends_on:
- check
kind: pipeline
name: docker-arm64
platform:
  arch: arm64
  os: linux
steps:
- commands:
  - git fetch origin --tags
  image: golang:1.16
  name: fetch-tags
  volumes:
  - name: gopath
    path: /go
- commands:
  - make static
  image: golang:1.16
  name: static
  volumes:
  - name: gopath
    path: /go
- image: plugins/docker
  name: container
  settings:
    auto_tag: true
    auto_tag_suffix: arm64
    password:
      from_secret: dockerhub_password
    repo: grafana/tanka
    username:
      from_secret: dockerhub_username
trigger:
  ref:
  - refs/heads/main
  - refs/heads/docker
  - refs/tags/v*
volumes:
- name: gopath
  temp: {}
---
depends_on:
- docker-amd64
- docker-arm64
kind: pipeline
name: manifest
steps:
- image: plugins/manifest
  name: manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: dockerhub_password
    spec: .drone/docker-manifest.tmpl
    username:
      from_secret: dockerhub_username
trigger:
  ref:
  - refs/heads/main
  - refs/heads/docker
  - refs/tags/v*
volumes:
- name: gopath
  temp: {}
---
get:
  name: pat
  path: infra/data/ci/github/grafanabot
kind: secret
name: grafanabot_pat
---
get:
  name: username
  path: infra/data/ci/docker_hub
kind: secret
name: dockerhub_username
---
get:
  name: password
  path: infra/data/ci/docker_hub
kind: secret
name: dockerhub_password
---
kind: signature
hmac: 6a78c1955d6f1b5530dbfbe8710b08a7f6db1466598d0fe451caec891ec506bd

...
