name: Lint PR title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  merge_group:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-pr-title:
    runs-on: ubuntu-24.04
    steps:
      - uses: grafana/shared-workflows/actions/lint-pr-title@823ed150196915a86971ab4beb899b0c80d835fe # lint-pr-title/v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
