name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          # https://github.com/actions/checkout/issues/1467 
          fetch-depth: 0
      - uses: ./.github/actions/setup-goversion
      - run: make cross
      - id: docker_tag
        run: echo "DOCKER_TAG=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
      - name: Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          body: |
            This is release `${{ env.GITHUB_REF_NAME }}` of Tanka (`tk`).

            ## Install instructions

            #### Binary:
            ```bash
            # download the binary (adapt os and arch as needed)
            $ curl -fSL -o "/usr/local/bin/tk" "https://github.com/grafana/tanka/releases/download/${{ env.GITHUB_REF_NAME }}/tk-linux-amd64"

            # make it executable
            $ chmod a+x "/usr/local/bin/tk"

            # have fun :)
            $ tk --help
            ```

            #### Docker container:
            https://hub.docker.com/r/grafana/tanka
            ```bash
            $ docker pull grafana/tanka:${{ env.DOCKER_TAG }}
            ```
          draft: true
          files: |
            dist/*
