name: Renovate
on:
  schedule:
    # Offset by 12 minutes to avoid busy times on the hour
    - cron: 12 */4 * * *

  pull_request:
    paths:
      - .github/renovate-config.json5
      - .github/workflows/renovate.yml
    types:
      - edited
      - opened
      - ready_for_review
      - synchronize

  push:
    branches:
      - main
    paths:
      - .github/renovate-config.json5
      - .github/workflows/renovate.yml

  workflow_dispatch:
    inputs:
      dry-run:
        description: "Run Renovate in dry-run mode"
        required: false
        default: false
        type: boolean

jobs:
  renovate:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/renovate-config.json5

      - name: Retrieve renovate secrets
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@9f37f656e063f0ad0b0bfc38d49894b57d363936 # get-vault-secrets/v1.2.1
        with:
          common_secrets: |
            GRAFANA_RENOVATE_APP_ID=grafana-renovate-app:app-id
            GRAFANA_RENOVATE_PRIVATE_KEY=grafana-renovate-app:private-key

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@0f859bf9e69e887678d5bbfbee594437cb440ffe # v2.1.0
        with:
          app-id: ${{ env.GRAFANA_RENOVATE_APP_ID }}
          private-key: ${{ env.GRAFANA_RENOVATE_PRIVATE_KEY }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@b11417b9eaac3145fe9a8544cee66503724e32b6 # v43.0.8
        with:
          configurationFile: .github/renovate-config.json5
          # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
          renovate-version: 39.42.4@sha256:c5d718e312cdacc0746e37f13c215ff498be28c51e50efd24c070ae29f5b636a
          token: ${{ steps.generate-token.outputs.token }}
        env:
          LOG_LEVEL: ${{ github.event_name == 'pull_request' && 'debug' || 'info' }}
          # For pull requests, this means we'll get the dependencies of the PR's
          # branch, so you can fix/change things and see the results in the PR's
          # run. By default, Renovate will clone the main/default branch.
          RENOVATE_BASE_BRANCHES: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || null }}
          # Dry run if the event is pull_request, or workflow_dispatch AND the dry-run input is true
          RENOVATE_DRY_RUN: ${{ (github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.dry-run == 'true')) && 'full' || null }}
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_USERNAME: GrafanaRenovateBot
